#!/bin/sh
# clear && clear

cd ${0%/*} || exit 1	# Run from this directory
par_switch
base_val='0'

echo ""
. $WM_PROJECT_DIR/bin/tools/RunFunctions		# Run functions

## CFD Processing
echo "Performing the CFD simulation:"
if [ "$par_switch" = "$base_val" ]; then
    runApplication $(getApplication)
else
    runParallel $(getApplication)
fi
echo ""
