#!/bin/sh
cd ${0%/*} || exit 1

echo " "
echo "Removing previous OpenFOAM installation if present..."
find . -type d -name 'foam' -exec rm -rv {} + > check.log 2>&1

echo " "
echo "Installing OpenFOAM..."
unzip foam.zip > zip.log 2>&1
echo "Installation finished"

rm -rf zip.log check.log
